# Generated by Django 4.2.3 on 2023-07-27 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mailing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailsender.mailing'),
        ),
        migrations.AddField(
            model_name='logs',
            name='mailing_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailsender.mailing'),
        ),
        migrations.AddField(
            model_name='mailtext',
            name='mailing_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailsender.mailing'),
        ),
    ]
