# Generated by Django 4.2.3 on 2023-07-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0002_customer_mailing_list_logs_mailing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус рассылки'),
        ),
    ]
