# Generated by Django 4.2.3 on 2023-07-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0003_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='mailing_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailsender.mailing'),
        ),
    ]
