# Generated by Django 4.2.3 on 2023-07-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0006_alter_mailing_mailing_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailtext',
            old_name='mailing_id',
            new_name='mailing',
        ),
    ]
