# Generated by Django 4.2.3 on 2023-08-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0013_mailtext_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtext',
            name='mailing',
        ),
        migrations.AddField(
            model_name='mailing',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailsender.mailtext'),
        ),
    ]
