# Generated by Django 4.2.3 on 2023-08-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0014_remove_mailtext_mailing_mailing_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mailing_list',
        ),
        migrations.AddField(
            model_name='mailing',
            name='customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailsender.customer'),
        ),
    ]
