# Generated by Django 4.2.3 on 2023-08-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0017_alter_mailing_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtext',
            name='mailings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailsender.mailing'),
        ),
    ]
