# Generated by Django 4.2.3 on 2023-08-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0018_mailtext_mailings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtext',
            name='mailings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailsender.mailing'),
        ),
    ]
