# Generated by Django 4.2.3 on 2023-08-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0019_alter_mailtext_mailings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtext',
            name='mailings',
        ),
    ]
