# Generated by Django 4.2.3 on 2023-08-18 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0020_remove_mailtext_mailings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mailsender.customer'),
        ),
    ]
