# Generated by Django 4.2.3 on 2023-08-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0021_alter_mailing_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='every_day',
            field=models.BooleanField(default=False, verbose_name='Ежедневная рассылка'),
        ),
    ]
