# Generated by Django 4.2.3 on 2023-08-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0022_alter_mailing_every_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='date_of_last_sending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время и дата последней рассылки'),
        ),
    ]
