# Generated by Django 4.2.3 on 2023-08-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0024_remove_logs_mailing_id_mailing_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='datetime_of_last_mailing',
            field=models.DateTimeField(verbose_name='Дата и время последней рассылки'),
        ),
    ]
