# Generated by Django 4.2.3 on 2023-08-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0025_alter_logs_datetime_of_last_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='datetime_of_last_mailing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней рассылки'),
        ),
    ]
